package com.midnight.compact

import com.intellij.psi.tree.IElementType

/** Token type produced by the lexer. */
class CompactTokenType(debugName: String) : IElementType(debugName, CompactLanguage) {
    override fun toString(): String = "CompactTokenType." + super.toString()
}

/**
 * Token type constants shared between the JFlex lexer and the rest of the plugin.
 *
 * The fields are annotated with [JvmField] so the Java code generated by JFlex can
 * reference them as plain static fields (e.g. `CompactTypes.KEYWORD`).
 */
object CompactTypes {
    @JvmField val KEYWORD = CompactTokenType("KEYWORD")
    @JvmField val TYPE = CompactTokenType("TYPE")
    @JvmField val BOOL_LITERAL = CompactTokenType("BOOL_LITERAL")
    @JvmField val IDENTIFIER = CompactTokenType("IDENTIFIER")
    @JvmField val STRING = CompactTokenType("STRING")
    @JvmField val NUMBER = CompactTokenType("NUMBER")
    @JvmField val LINE_COMMENT = CompactTokenType("LINE_COMMENT")
    @JvmField val BLOCK_COMMENT = CompactTokenType("BLOCK_COMMENT")

    @JvmField val LPAREN = CompactTokenType("LPAREN")
    @JvmField val RPAREN = CompactTokenType("RPAREN")
    @JvmField val LBRACE = CompactTokenType("LBRACE")
    @JvmField val RBRACE = CompactTokenType("RBRACE")
    @JvmField val LBRACKET = CompactTokenType("LBRACKET")
    @JvmField val RBRACKET = CompactTokenType("RBRACKET")

    @JvmField val SEMICOLON = CompactTokenType("SEMICOLON")
    @JvmField val COMMA = CompactTokenType("COMMA")
    @JvmField val DOT = CompactTokenType("DOT")
    @JvmField val OPERATOR = CompactTokenType("OPERATOR")
}
